server:
  port: 8761

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: eureka-server

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false
    peer-node-read-timeout-ms: 30000  
  instance:
    lease-renewal-interval-in-seconds: 10  
    lease-expiration-duration-in-seconds: 30 

logging:
  level:
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always