version: '3.8'

services:
  db:
    image: mysql:8.0.39
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_password}
      MYSQL_DATABASE: Stock
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./erd.sql:/docker-entrypoint-initdb.d/erd.sql
    networks:
      - my-network

  redis:
    image: redis:6.2
    container_name: redis-cache
    ports:
      - "6379:6379"
    networks:
      - my-network

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    container_name: kafka-server
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - my-network
    depends_on:
      - zookeeper

  zookeeper:
    image: zookeeper:3.7.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - my-network

  auth-service:
    build:
      context: .
      dockerfile: authentication/Dockerfile
    container_name: auth-service
    ports:
      - "8082:8082"
    depends_on:
      - db
      - redis
      - kafka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/Stock
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${DB_password}
      - SPRING_REDIS_HOST=redis
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9093
      - SERVERS=db
      - KAFKA_SERVERS=kafka
      - REDIS_HOST=redis
      - JWT_SECRET=${JWT_SECRET}
      - EMAIL=${EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    networks:
      - my-network

  user-service:
    build:
      context: .
      dockerfile: user_service/Dockerfile
    container_name: user-service
    ports:
      - "8081:8081"
    depends_on:
      - db
      - kafka
      - auth-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/Stock
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${DB_password}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9093
      - SERVERS=db
      - KAFKA_SERVERS=kafka
    networks:
      - my-network

volumes:
  mysql-data:

networks:
  my-network:
    driver: bridge