services:
  jenkins:
    image: jenkins/jenkins:lts
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - my-network
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    command: >
      bash -c "
      apt-get update && 
      apt-get -y install apt-transport-https ca-certificates curl gnupg2 software-properties-common && 
      curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add - && 
      add-apt-repository \"deb [arch=amd64] https://download.docker.com/linux/debian $$(lsb_release -cs) stable\" && 
      apt-get update && 
      apt-get -y install docker-ce-cli &&
      chown -R jenkins:jenkins /var/jenkins_home &&
      su jenkins -c \"/usr/local/bin/jenkins.sh\"
      "

  db:
    image: mysql:8.0.39
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_LOG_CONSOLE: "true"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./erd.sql:/docker-entrypoint-initdb.d/erd.sql
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 10s
      retries: 10

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    container_name: kafka-server
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      zookeeper:
        condition: service_healthy
    networks:
      - my-network

  zookeeper:
    image: zookeeper:3.7.0
    container_name: zookeeper
    volumes:
      - ./zookeeper/data:/data
      - ./zookeeper/datalog:/datalog
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888;2181
    ports:
      - "2181:2181"
    networks:
      - my-network
    healthcheck:
      test: ["CMD-SHELL", "zkServer.sh status || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  api-gateway:
    build:
      context: .
      dockerfile: api_gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=${MODE:-prod}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - JAVA_TOOL_OPTIONS=-Djavax.net.debug=ssl,handshake
      - SSL_KEY_STORE_PASSWORD=${SSL_KEY_STORE_PASSWORD}
    env_file:
      - .env
    networks:
      - my-network
    volumes:
      - ./api_gateway/src/main/resources:/app/ssl
      - ./api_gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./api_gateway/convert_cert.sh:/app/convert_cert.sh
      - ./api_gateway/start.sh:/app/start.sh
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  eureka-server:
    build:
      context: .
      dockerfile: eureka_server/Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
      build:
        context: .
        dockerfile: user_service/Dockerfile
      container_name: user-service
      ports:
        - "8444:8444" 
        - "3001:443" 
      depends_on:
        eureka-server:
          condition: service_healthy
        db:
          condition: service_healthy
        redis:
          condition: service_healthy
        kafka:
          condition: service_healthy
      env_file:
        - .env
      volumes:
        - user-uploads:/app/uploads/profile_images
        - ./user_service/src/main/resources:/app/ssl
      environment:
        - SPRING_PROFILES_ACTIVE=${MODE:-prod}
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
        - SSL_KEY_STORE_PASSWORD=${SSL_KEY_STORE_PASSWORD}
        - SERVER_PORT=8444
      networks:
        - my-network
      healthcheck:
        test: ["CMD", "curl", "-k", "-f", "https://localhost:8444/actuator/health"]
        interval: 30s
        timeout: 10s
        retries: 5

  newsfeed-service:
    build:
      context: .
      dockerfile: newsfeed_service/Dockerfile
    container_name: newsfeed-service
    ports:
      - "8083:8083"
      - "3002:80"  
    depends_on:
      eureka-server:
        condition: service_healthy
      db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=${MODE:-prod}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  social-service:
    build:
      context: .
      dockerfile: social_service/Dockerfile
    container_name: social-service
    ports:
      - "8084:8084"
      - "3003:80"  
    depends_on:
      eureka-server:
        condition: service_healthy
      db:
        condition: service_healthy
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=${MODE:-prod}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  stock-service:
    build:
      context: .
      dockerfile: stock_service/Dockerfile
    container_name: stock-service
    ports:
      - "8085:8085"
      - "3004:80"  
    depends_on:
      kafka:
        condition: service_healthy
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=${MODE:-prod}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${KAFKA_SERVERS}:${KAFKA_PORT}
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mysql-data:
  jenkins_home:
  user-uploads:
  ssl:
    driver: local
    driver_opts:
      type: none
      device: ./ssl
      o: bind

networks:
  my-network:
    name: my-network
    driver: bridge