version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    privileged: true
    user: root
    ports:
      - 8010:8010
      - 50000:50000
    container_name: jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - my-network

  db:
    image: mysql:8.0.39
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: Stock
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./erd.sql:/docker-entrypoint-initdb.d/erd.sql
    networks:
      - my-network

  redis:
    image: redis:6.2
    container_name: redis-cache
    ports:
      - "6379:6379"
    networks:
      - my-network

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    container_name: kafka-server
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - my-network
    depends_on:
      - zookeeper

  zookeeper:
    image: zookeeper:3.7.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - my-network

  auth-service:
    build:
      context: .
      dockerfile: authentication/Dockerfile
    container_name: auth-service
    ports:
      - "8082:8082"
    depends_on:
      - db
      - redis
      - kafka
    env_file:
      - .env
    networks:
      - my-network

  user-service:
    build:
      context: .
      dockerfile: user_service/Dockerfile
    container_name: user-service
    ports:
      - "8081:8081"
    depends_on:
      - db
      - kafka
    env_file:
      - .env
    networks:
      - my-network

  newsfeed-service:
    build:
      context: .
      dockerfile: newsfeed_service/Dockerfile
    container_name: newsfeed-service
    ports:
      - "8083:8083"
    depends_on:
      - db
      - kafka
    env_file:
      - .env
    networks:
      - my-network

  social-service:
    build:
      context: .
      dockerfile: social_service/Dockerfile
    container_name: social-service
    ports:
      - "8084:8084"
    depends_on:
      - db
      - kafka
    env_file:
      - .env
    networks:
      - my-network

  integration-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: integration-test
    depends_on:
      - auth-service
      - user-service
      - newsfeed-service
      - social-service
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/Stock
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    networks:
      - my-network
    command: ["./gradlew", "integrationTest"]

volumes:
  mysql-data:
  jenkins_home:

networks:
  my-network:
    driver: bridge