server:
  port: 8081
  ssl:
    enabled: true
    key-store: classpath:apigateway.p12
    key-store-password: ${SSL_KEY_STORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: apigateway

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "https://localhost:3001"
              - "https://localhost:3002"
              - "https://localhost:3003"
              - "https://localhost:3004"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

app:
  jwt:
    secret: ${JWT_SECRET}
    expirationInMs: 3600000

resilience4j:
  thread-pool-bulkhead:
    enabled: false
  ratelimiter:
    instances:
      default:
        limitForPeriod: 10
        limitRefreshPeriod: PT1S
        timeoutDuration: PT0.1S

logging:
  level:
    root: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"