server:
  port: 8081

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: 
              - "http://localhost:3001"
              - "http://localhost"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
        - id: newsfeed_service
          uri: lb://NEWSFEED-SERVICE
          predicates:
            - Path=/api/newsfeed/**
          filters:
            - AuthenticationFilter
            - RateLimitingFilter
        - id: social_service
          uri: lb://SOCIAL-SERVICE
          predicates:
            - Path=/api/social/**
          filters:
            - AuthenticationFilter
            - RateLimitingFilter
        - id: user_service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/auth/**
          filters:
            - RateLimitingFilter
        - id: user_service_protected
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/auth/check, /api/auth/logout, /api/auth/password, /api/auth/users/**
          filters:
            - AuthenticationFilter
            - RateLimitingFilter
        - id: stock_service
          uri: lb://STOCK-SERVICE
          predicates:
            - Path=/api/stocks/**
          filters:
            - AuthenticationFilter
            - RateLimitingFilter

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true

app:
  jwt:
    secret: ${JWT_SECRET}
    expirationInMs: 3600000

resilience4j:
  thread-pool-bulkhead:
    enabled: false
  ratelimiter:
    instances:
      default:
        limitForPeriod: 10
        limitRefreshPeriod: PT1S
        timeoutDuration: PT0.1S

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG